import {
  PagePanel as Page,
  SectionPanel as Section,
  ColumnPanel as Column,
  TextPanel as Text,
  ImagePanel as Image,
  GroupPanel as Group,
  ButtonPanel as Button,
  DividerPanel as Divider,
  WrapperPanel as Wrapper,
  SpacerPanel as Spacer,
  RawPanel as Raw,
  AccordionPanel as Accordion,
  AccordionElementPanel as AccordionElement,
  AccordionTitlePanel as AccordionTitle,
  AccordionTextPanel as AccordionText,
  CarouselPanel as Carousel,
  HeroPanel as Hero,
  NavbarPanel as Navbar,
  SocialPanel as Social,
  TablePanel as Table,
} from '../block-panels/standard';
import { AdvancedTablePanel as AdvancedTable } from '../block-panels/advanced/advancedTablePanel';
import { BasicType, AdvancedType } from '@wa-dev/email-editor-shared/types';

export const blocks = {
  [BasicType.PAGE]: Page,
  [BasicType.SECTION]: Section,
  [BasicType.COLUMN]: Column,
  [BasicType.TEXT]: Text,
  [BasicType.IMAGE]: Image,
  [BasicType.GROUP]: Group,
  [BasicType.BUTTON]: Button,
  [BasicType.DIVIDER]: Divider,
  [BasicType.WRAPPER]: Wrapper,
  [BasicType.SPACER]: Spacer,
  [BasicType.RAW]: Raw,
  [BasicType.ACCORDION]: Accordion,
  [BasicType.ACCORDION_ELEMENT]: AccordionElement,
  [BasicType.ACCORDION_TITLE]: AccordionTitle,
  [BasicType.ACCORDION_TEXT]: AccordionText,
  [BasicType.CAROUSEL]: Carousel,
  [BasicType.HERO]: Hero,
  [BasicType.NAVBAR]: Navbar,
  [BasicType.SOCIAL]: Social,
  [BasicType.TABLE]: Table,

  [AdvancedType.TEXT]: Text,
  [AdvancedType.IMAGE]: Image,
  [AdvancedType.BUTTON]: Button,
  [AdvancedType.DIVIDER]: Divider,
  [AdvancedType.SPACER]: Spacer,
  [AdvancedType.ACCORDION]: Accordion,
  [AdvancedType.CAROUSEL]: Carousel,
  [AdvancedType.NAVBAR]: Navbar,
  [AdvancedType.SOCIAL]: Social,
  [AdvancedType.TABLE]: AdvancedTable,

  [AdvancedType.HERO]: Hero,
  [AdvancedType.WRAPPER]: Wrapper,
  [AdvancedType.SECTION]: Section,
  [AdvancedType.GROUP]: Group,
  [AdvancedType.COLUMN]: Column,
};

export { BasicType, AdvancedType };
